# Model arguments
# For definitions, see: src/h4/training/config.py

model_name_or_path: <ORG>/numina-math-7b-tir
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
overwrite_hub_revision: true
# Data training arguments
# For definitions, see: src/h4/training/config.py
block_size: 1024
chat_template: "{% for message in messages %}{% if (message['role'] == 'system')%}{{ '' }}{% elif (message['role'] == 'user')%}{{ '### Problem: ' + message['content'] + '\n' }}{% elif (message['role'] == 'assistant')%}{{ '### Solution: ' + message['content'] + '\n' }}{% endif %}{% if loop.last and message['role'] == 'user' and add_generation_prompt %}{{ '### Solution: ' }}{% endif %}{% endfor %}"
dataset_mixer: 
  AI-MO/tora-chosen-v0.7: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 8

# Training arguments with sensible defaults
# Add other options from here: https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/trainer#transformers.TrainingArguments
bf16: true
do_eval: true
do_train: true
evaluation_strategy: epoch # One of ["no", "steps", "epoch"]
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: <ORG>/numina-math-7b-tir
hub_private_repo: true
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: passive
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 4
output_dir: data/numina-math-7b-tir
hub_model_revision: main
run_name: numina-math-7b-tir
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 4
push_to_hub_revision: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
save_total_limit: 1
save_steps: 0.1
seed: 42
wandb_run_group: numina-math-7b-tir # Name of the W&B group to collect all runs of this experiment under. Use double-digits for {idx}, starting from 00.
wandb_run_id: null # Set this to a globally unique string if you want a descriptive name of your run
wandb_tags: # Use tags to filter runs on WandB
- sft
warmup_ratio: 0.1